name: akgec_erp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.1.0
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.0.0
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
